---
title: DADI
collections:
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    image:
    description:
    button:
      title:
      url:
- scope:
    path: ''
    type: blog_tags
  values:
    layout: tag
  values:
    image:
    link:
baseurl: ""
url: https://data-accelerator.github.io
description: DADI home
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: styles/
  style: compressed
per_page: 12
date_format: "%b %d, %Y"
logo: "/assets/dadi-logo.png"
future: true
header_nav:
  Blog: "/blog/"
  校招: "/blog/JoinUs"
footer_nav:

